### ISSUE TITLE
Issue with using hybrid mode

### ISSUE THREAD

**Issue by gottlike** [socketry/falcon#117]
Sorry for spamming you lately :sweat_smile: 

For my simple API service I was doing local (4-core Linux laptop) benchmarking between Puma and Falcon and noticed that Puma hit 25k requests/s without errors when benchmarking 1000 connection through wrk (`docker run --rm --net="host" skandyla/wrk -t2 -c1000 -d10 "http://localhost:9292"`) - whereas Falcon "only" hit 16k max and threw some errors near the end of the run:

`bundle exec falcon serve --bind http://localhost:9292`
```
16.31s    error: Async::Task [oid=0x2afaf43f2f2c] [pid=5824] [2020-05-05 10:25:59 +0200]
               |   Errno::EPIPE: Broken pipe
               |   → /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/2.6.0/socket.rb:456 in `__write_nonblock'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/2.6.0/socket.rb:456 in `write_nonblock'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/generic.rb:216 in `async_send'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/generic.rb:62 in `block in wrap_blocking_method'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/generic.rb:156 in `write'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/stream.rb:160 in `block in flush'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.25.2/lib/async/semaphore.rb:80 in `acquire'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/stream.rb:155 in `flush'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/protocol-http1-0.12.0/lib/protocol/http1/connection.rb:303 in `write_fixed_length_body'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/protocol-http1-0.12.0/lib/protocol/http1/connection.rb:365 in `write_body'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-http-0.52.0/lib/async/http/protocol/http1/server.rb:97 in `each'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-http-0.52.0/lib/async/http/server.rb:53 in `accept'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/server.rb:32 in `block in accept_each'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.29.0/lib/async/io/socket.rb:73 in `block in accept'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.25.2/lib/async/task.rb:258 in `block in make_fiber'
```

I thought that maybe "hybrid" mode would perform better, but was unable to get it to run:

`bundle exec falcon serve --bind http://localhost:9292 --hybrid --count 128`
```
0.36s    error: Async::Container::Hybrid [oid=0x2b2078b15b34] [pid=6009] [2020-05-05 10:29:02 +0200]
               | pid 6070 exit 1
 0.36s    error: Async::Container::Process [pid=6071] [2020-05-05 10:29:02 +0200]
               |   NameError: uninitialized constant Async::Container::Threaded::Container
               |   → /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/hybrid.rb:37 in `block (2 levels) in run'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/process.rb:77 in `block (2 levels) in fork'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/process.rb:72 in `fork'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/process.rb:72 in `block in fork'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/process.rb:106 in `initialize'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/process.rb:71 in `new'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/process.rb:71 in `fork'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/forked.rb:35 in `start'
               |     /home/gottlike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/async-container-0.16.4/lib/async/container/generic.rb:134 in `block in spawn'
```

Any hints on what I'm doing wrong?

**Comment by ioquatix** [comment]
Hybrid mode was an experiment and is not even tested, that's the problem. So you didn't do anything wrong, it's just not on my radar as being broken, but it looks like it is.

`wrk` simply terminates the connections rather than waiting for the request to finish. As this is unexpected, falcon reports it as EPIPE or ECONNRESET.

It's not spamming issues, it's a good issue.

**Comment by gottlike** [comment]
Alright, got it. Feel free to close the issue then - or keep it open if you intend to fix/finish hybrid mode eventually :)

**Comment by ioquatix** [comment]
It should be fixed.

**Comment by gottlike** [comment]
I just pulled the latest version from Github, but still get the same errors.

**Comment by ioquatix** [comment]
![image](https://user-images.githubusercontent.com/30030/82147978-84027200-98a5-11ea-97fe-561b3a27ff66.png)

This should be fixed now, can you please try updating async-container to v0.16.5 and testing again? Thanks!

**Comment by ioquatix** [comment]
> I just pulled the latest version from Github, but still get the same errors.

Sorry, I was so unclear. I said "It should be fixed." as in, "I should fix it" rather than "It is fixed". Sorry for the confusion.

**Comment by gottlike** [comment]
Now it's running fine, thanks! :+1:

**Comment by ioquatix** [comment]
Thanks for reporting back and closing the issue :)
